from datetime import datetime
BOARDS = [
    {'id': 1, 'name': 'Набережная в сторону заречья', 'description': 'Набережная в сторону заречья','id_busstop_yandex': 10008334, 'id_tramstop_yandex': 10008444,
        'zabbix_node_name': 'board_id1', 'id_busstop_pikas': 92878, 'id_tramstop_pikas': 177, 'boards_data': None, 'datatime_update_pikas': datetime.datetime(2021, 7, 13, 10, 2, 51, 685983)},
    {'id': 2, 'name': 'Набережная в сторону центра', 'description': 'Набережная в сторону центра', 'id_busstop_yandex': 10008333, 'id_tramstop_yandex': 10008443,
        'zabbix_node_name': 'board_id2', 'id_busstop_pikas': 92635, 'id_tramstop_pikas': 151, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 3, 'name': 'ДКМ', 'description': 'в ЗШК', 'id_busstop_yandex': 10008384, 'id_tramstop_yandex': None, 'zabbix_node_name': 'board_id3',
        'id_busstop_pikas': 97847, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 4, 'name': 'Кванториум', 'description': 'в город', 'id_busstop_yandex': 10008383, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id4', 'id_busstop_pikas': 97938, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 5, 'name': 'СКЗ "Алмаз"', 'description': 'в ЗШК', 'id_busstop_yandex': 10008382, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id5', 'id_busstop_pikas': 92679, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 6, 'name': 'Дом торговли', 'description': 'в город', 'id_busstop_yandex': 10008381, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id6', 'id_busstop_pikas': 92848, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 7, 'name': 'ДК "Амофос"', 'description': 'в заречье', 'id_busstop_yandex': 10008362, 'id_tramstop_yandex': 10008442,
        'zabbix_node_name': 'board_id7', 'id_busstop_pikas': 92897, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 8, 'name': 'ТЦ "Рассвет"', 'description': 'в город', 'id_busstop_yandex': 10008363, 'id_tramstop_yandex': 10008441,
        'zabbix_node_name': 'board_id8', 'id_busstop_pikas': 92607, 'id_tramstop_pikas': 150, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 9, 'name': 'Городской рынок', 'description': 'в сторону завода', 'id_busstop_yandex': 10008337, 'id_tramstop_yandex': 10008625,
        'zabbix_node_name': 'board_id9', 'id_busstop_pikas': 98081, 'id_tramstop_pikas': 153, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 10, 'name': 'Городской рынок', 'description': 'в заречье', 'id_busstop_yandex': 10008338, 'id_tramstop_yandex': 10008624,
        'zabbix_node_name': 'board_id10', 'id_busstop_pikas': 98777, 'id_tramstop_pikas': 175, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 11, 'name': 'Рынок в ЗШК', 'description': 'Октябрьский пр. 60', 'id_busstop_yandex': 10008389, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id11', 'id_busstop_pikas': 97910, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 12, 'name': 'улица Наседкина, 21', 'description': 'в город', 'id_busstop_yandex': 10008399, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id12', 'id_busstop_pikas': 97679, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 13, 'name': 'Ленина, 76', 'description': 'в строну завода', 'id_busstop_yandex': 10008378, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id13', 'id_busstop_pikas': 92664, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 14, 'name': 'Краснодонцев, 23', 'description': 'в город', 'id_busstop_yandex': 10008322, 'id_tramstop_yandex': None, 'zabbix_node_name': 'board_id14', 'id_busstop_pikas': 92553,
     'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 15, 'name': 'Наседкина, 3', 'description': 'в город', 'id_busstop_yandex': 10008400, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id15', 'id_busstop_pikas': 97900, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 16, 'name': 'Октябрьский, 36', 'description': 'в город', 'id_busstop_yandex': 10008387, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id16', 'id_busstop_pikas': 97916, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 17, 'name': 'Советский, 126', 'description': 'ЧВИИРЭ', 'id_busstop_yandex': 10008477, 'id_tramstop_yandex': 10008479,
        'zabbix_node_name': 'board_id17', 'id_busstop_pikas': 94545, 'id_tramstop_pikas': 185, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 18, 'name': 'Проезжая, 4', 'description': 'ФМК', 'id_busstop_yandex': 10008468, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id18', 'id_busstop_pikas': 95373, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 19, 'name': 'Строителей, 31', 'description': 'от завода', 'id_busstop_yandex': 10008507, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id19', 'id_busstop_pikas': 92822, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 20, 'name': 'Городецкая, 24', 'description': 'из города', 'id_busstop_yandex': 10008393, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id20', 'id_busstop_pikas': 99175, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 21, 'name': 'площадь Милютина', 'description': 'ул. Ленина 39А', 'id_busstop_yandex': 10008498, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id21', 'id_busstop_pikas': 92862, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 22, 'name': 'улица Суворова', 'description': 'в сторону города, пр-т Победы 127', 'id_busstop_yandex': 10008368, 'id_tramstop_yandex': 10008370,
        'zabbix_node_name': 'board_id22', 'id_busstop_pikas': 92592, 'id_tramstop_pikas': 148, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 23, 'name': 'Советский, 76', 'description': 'от Соборной горки', 'id_busstop_yandex': 10008496, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id23', 'id_busstop_pikas': 92865, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 24, 'name': 'Вокзал', 'description': 'в ЗШК', 'id_busstop_yandex': 10008482, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id24', 'id_busstop_pikas': 94333, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 25, 'name': 'Вокзал', 'description': 'в заягорбский и фанеру', 'id_busstop_yandex': 10008481, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id25', 'id_busstop_pikas': 94532, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 26, 'name': 'Советский, 65', 'description': 'к Соборной горке', 'id_busstop_yandex': 10008497, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id26', 'id_busstop_pikas': 92653, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 27, 'name': 'Новый век', 'description': 'в город', 'id_busstop_yandex': 10008408, 'id_tramstop_yandex': 10008410,
        'zabbix_node_name': 'board_id27', 'id_busstop_pikas': 93927, 'id_tramstop_pikas': 147, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 28, 'name': 'Красный ткач', 'description': 'в город', 'id_busstop_yandex': 10008364, 'id_tramstop_yandex': 10008367,
        'zabbix_node_name': 'board_id28', 'id_busstop_pikas': 92602, 'id_tramstop_pikas': 149, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 29, 'name': 'Проезжая, 5', 'description': None, 'id_busstop_yandex': 10008469, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id29', 'id_busstop_pikas': 95223, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 30, 'name': 'Ленина, 99', 'description': 'от завода', 'id_busstop_yandex': 10008379, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id30', 'id_busstop_pikas': 92857, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 31, 'name': 'Ледовый дворец', 'description': 'в город', 'id_busstop_yandex': 10008538, 'id_tramstop_yandex': None,
        'zabbix_node_name': 'board_id31', 'id_busstop_pikas': 200792, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 98, 'name': 'Тестовая панель2', 'description': 'Тестовая панель', 'id_busstop_yandex': None, 'id_tramstop_yandex': None,
        'zabbix_node_name': None, 'id_busstop_pikas': 97938, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None},
    {'id': 99, 'name': 'Тестовая панель', 'description': 'Тестовая панель для отладки изображений', 'id_busstop_yandex': None, 'id_tramstop_yandex': None, 'zabbix_node_name': None, 'id_busstop_pikas': 97938, 'id_tramstop_pikas': None, 'boards_data': None, 'datatime_update_pikas': None}
]
